namePrefix: production-
commonLabels:
  variant: production
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am production!
resources:
- ../overlays/application
patchesStrategicMerge:
- deployment.yaml
