namePrefix: production-
commonLabels:
  variant: production
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am production from hello-world-1!
resources:
- ../hello-world-1/overlays/application
