apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
      app.kubernetes.io/instance: hello-world-0.1.0
      app.kubernetes.io/component: hello-world
      app.kubernetes.io/version: 0.1.0
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    type: hello-world
    version: v1beta1
    description: ""
    maintainers: []
    owners: []
    keywords:
     - hello-world
     - kustomize
    links:
    - description: About
      url: ""
  addOwnerRef: true
