apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: hello-world
  app.kubernetes.io/instance: hello-world-0.1.0
  app.kubernetes.io/component: hello-world
  app.kubernetes.io/version: 0.1.0
